#pragma once

#define QEMU_VIRT_PLIC_BASE 0x0c000000

#define SIFIVE_PLIC_PRIORITY_BASE (QEMU_VIRT_PLIC_BASE)
#define SIFIVE_PLIC_PENDING_BASE (QEMU_VIRT_PLIC_BASE + 0x1000)
#define SIFIVE_PLIC_M_ENABLE_BASE (QEMU_VIRT_PLIC_BASE + 0x2000)
#define SIFIVE_PLIC_S_ENABLE_BASE (QEMU_VIRT_PLIC_BASE + 0x2080)
#define SIFIVE_PLIC_PRIORITY_THRESHOLD (QEMU_VIRT_PLIC_BASE + 0x201000)
#define SIFIVE_PLIC_M_CLAIM_COMPLETE (QEMU_VIRT_PLIC_BASE + 0x200004)
#define SIFIVE_PLIC_S_CLAIM_COMPLETE (QEMU_VIRT_PLIC_BASE + 0x201004)

#define SIFIVE_NUM_OF_INTERRUPT 5

#define SIFIVE_IRQ_NUMBER_VIRTIO_IRQ    (1)
#define SIFIVE_IRQ_NUMBER_VIRTIO_COUNT  (8)
#define SIFIVE_IRQ_NUMBER_UART0         (10)
#define SIFIVE_IRQ_NUMBER_PCIE_IRQ      (32)
#define SIFIVE_IRQ_NUMBER_MAX           (32)

#define PLIC_INTE_PRIORITY_REG_PRIORITY (0x7)
#define PLIC_INTE_PRIORITY_REG_RESERVED (0xfffffff8)
