#pragma once

// read mode
#define RECEIVE_HOLDING_REGISTER 0b000
#define INTERRUPT_STATUS_REGISTER 0b010
#define LINE_STATUS_REGISTER 0b101
#define MODEM_STATUS_REGISTER 0b110
#define SCRATCHPAD_REGISTER_READ 0b111

// write mode
#define TRANSMIT_HOLDING_REGISTER 0b000
#define LSB_OF_DIVISOR_LATCH 0b000
#define INTERRUPT_ENABLE_REGISTER 0b001
#define MSB_OF_DIVISOR_LATCH 0b001
#define FIFO_CONTROL_REGISTER 0b010
#define LINE_CONTROL_REGISTER 0b011
#define MODEM_CONTROL_REGISTER 0b100
#define SCRATCHPAD_REGISTER_WRITE 0b111


